# Roadiz travis setup
# Ambroise Maupate
language: php
sudo: required
php:
  - 7.2
  - 7.3
  - 7.4

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - vendor/bin/phpunit -v --bootstrap=tests/bootstrap.php --whitelist ./src --coverage-clover ./build/logs/clover.xml tests/
  - vendor/bin/phpcs --report=full --report-file=./report.txt --extensions=php --warning-severity=0 --standard=PSR2 -p ./src
  - vendor/bin/phpstan analyse -c phpstan.neon -l 3 src
