# Roadiz travis setup
# Ambroise Maupate
language: php
sudo: required
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - ENABLE_SECOND_LEVEL_CACHE=0 php vendor/bin/phpunit -v --bootstrap=tests/bootstrap.php --coverage-clover ./build/logs/clover.xml tests/
  - vendor/bin/phpcs --report=full --report-file=./report.txt --extensions=php --warning-severity=0 --standard=PSR2 --ignore="*/node_modules/*,*/.AppleDouble,*/vendor/*,*/cache/*,*/gen-src/*,*/tests/*,*/bin/*" -p ./

